# site settings

title: trisfproject
description: 
I turn coffee :coffee: into code, use tabs over spaces.
taglong: I turn coffee :coffee: into code, use tabs over spaces.
tagshort: trisf project 
url: trisfproject.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/trisfproject/trisfproject.github.io

# author settings

author:
  name: trisf project 
  email: trisfproject@gmail.com
photo: /assets/jpg/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
